name: auto-generate-document
on:
  push:
    branches:
      - main
jobs:
  generate-document:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install doxygen
      run: |
        sudo apt update
        sudo apt install doxygen graphviz

    - name: generate document
      run: doxygen

    - name: git push
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git config user.name  "action-user"
          git config user.email "action@github.com"
          git add docs/
          git commit -m "document自動生成"
          git push
        else
          echo "no changes, skip push"
        fi
