name: Generate document and push to doc-repo

on:
  push:
    branches:
      - main

jobs:
  doc-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate document
        run: |
          sudo apt update
          sudo apt install doxygen graphviz
          doxygen

      - name: Setup git repogitories
        env:
          REPO_DEPLOY_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$REPO_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.email "action@github.com"
          git config --global user.name "action-user"
          git clone git@github.com:cct-watanabe/test2.git
          mv doc/ test2/

      - name: Push Document to doc-repo
        run: |
          cd test2
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "${{ steps.setup_description.outputs.content }}"
            git push origin main
          else
            echo "no changes, skip push"
          fi
