name: Generate document and push to another-repo

on:
  push:
    branches:
      - main

jobs:
  doc-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate document
        run: |
          apt update
          apt install doxygen graphviz
          doxygen
      - name: Git push document
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_IO_REPO_DEPLOY_KEY }}
        with:
          source_file: "docs/"
          destination_repo: "p"
          destination_folder: "./"
          destination_branch: "main"
          user_email: "action@github.com"
          user_name: "action-user"
          commit_message: ${{ steps.setup_description.outputs.content }}
