name: Generate document and push to doc-repo

on:
  push:
    branches:
      - main

jobs:
  doc-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate document
        run: |
          sudo apt update
          sudo apt install doxygen graphviz
          doxygen

      - name: Setup git repogitories
        env:
          REPO_DEPLOY_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
        run: |
          echo "$REPO_DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global user.email "action@github.com"
          git config --global user.name "action-user"
          cd docs
          git config remote.origin.url "git@github.com:cct-watanabe/test2.git"
          git checkout main
          git pull origin main

      - name: Push Document to doc-repo
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "${{ steps.setup_description.outputs.content }}"
            git push origin main
          else
            echo "no changes, skip push"
          fi
